version: '3.5'  

services: 
    backend: 
      image: back:latest
      environment: 
        - REQUEST_ORIGIN=http://localhost:5000
      ports: 
        - 8000:8080  
      command: [ "./server"]
        

    frontend: 
      image: front:latest
      environment: 
        - REACT_APP_BACKEND_URL=http://localhost:8080
      ports:
        - 4000:5000 
      command: [ "serve" ,"-s", "-l", "5000" , "build" ]  