version: '3.5'

services:
  frontend:
    build: ./ml-kurkkumopo-frontend
    image: frnotend:latest
    environment: 
        - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
        - 3000:3000 
    command: [ "serve" ,"-s", "-l", "3000" , "build" ]    

  backend:
    build: ./ml-kurkkumopo-backend
    image: backend:latest
    environment: 
            - REQUEST_ORIGIN=http://localhost:3000
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    command: ["python", "-u", "app.py"]  
  
  training:
    build: ./ml-kurkkumopo-training
    image: tarining:latest
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    command: ["python", "-u", "train.py"]  
volumes:
  model:
  imgs: